version: '3.1'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Ashu@143#"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: Ashu@143#
      DB_NAME: postgres
    depends_on:
      - db
    ports:
      - "8000:8000"
