version: '3.1'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: 
      DB_PASS: 
      DB_NAME: 
    depends_on:
      - db
    ports:
      - "8000:8000"
